

$(document).ready(function(){$("#countdown").countdown({htmlTemplate:'<div id="countdown_day" class="countdown count"><div><span>%d</span>أيام</div></div><div id="coundown_hour" class="countdown count"><div><span>%h</span>ساعات</div></div><div id="coundown_min" class="countdown count"><div><span>%i</span>دقيقة</div></div><div id="coundown_sec" class="countdown count c_last"><div><span>%s</span>ثانية</div></div>',date:endDate,hoursOnly:!1,leadingZero:!0})}),function(e){e.fn.countdown=function(t){var n={date:null,updateTime:1e3,htmlTemplate:"%d <span class='cd-time'>days</span> %h <span class='cd-time'>hours</span> %i <span class='cd-time'>mins</span> %s <span class='cd-time'>sec</span>",minus:!1,onChange:null,onComplete:null,onResume:null,onPause:null,leadingZero:!1,offset:null,servertime:null,hoursOnly:!1,minsOnly:!1,secsOnly:!1,weeks:!1,hours:!1,yearsAndMonths:!1,direction:"down",stopwatch:!1},a=Array.prototype.slice,o=window.clearInterval,d=Math.floor,i=36e5,r=31556926,s=2629743.83,c=604800,u=86400,l=3600,m=60,p=1,h=/(%y|%m|%w|%d|%h|%i|%s)/g,v=/%y/,f=/%m/,g=/%w/,j=/%d/,w=/%h/,D=/%i/,y=/%s/,C=function(e){var t=new Date,n=e.data("jcdData")
return n?(t=null!==n.offset?T(n.offset):T(null,n.difference),t.setMilliseconds(0),t):new Date},T=function(e,t){var n,a,o,d=new Date
return null===e?a=d.getTime()-t:(n=e*i,o=d.getTime()- -d.getTimezoneOffset()/60*i+n,a=d.setTime(o)),new Date(a)},L=function(){var e,t,n,a,i,T,L,O,M,P,I,x,b=this,R="",A=function(e){var t
return t=d(x/e),x-=t*e,t},_=b.data("jcdData")
return _?(e=_.htmlTemplate,t=C(b),n=_.dateObj,n.setMilliseconds(0),a="down"===_.direction?n.getTime()-t.getTime():t.getTime()-n.getTime(),x=Math.round(a/1e3),O=A(u),M=A(l),P=A(m),I=A(p),_.yearsAndMonths&&(x+=O*u,i=A(r),T=A(s),O=A(u)),_.weeks&&(x+=O*u,L=A(c),O=A(u)),_.hoursOnly&&(M+=24*O,O=0),_.minsOnly&&(P+=60*M+24*O*60,O=M=0),_.secsOnly&&(I+=60*P,O=M=P=0),_.yearsLeft=i,_.monthsLeft=T,_.weeksLeft=L,_.daysLeft=O,_.hrsLeft=M,_.minsLeft=P,_.secLeft=I,60===I&&(I=0),_.leadingZero&&(10>O&&!_.hoursOnly&&(O="0"+O),10>i&&(i="0"+i),10>T&&(T="0"+T),10>L&&(L="0"+L),10>M&&(M="0"+M),10>P&&(P="0"+P),10>I&&(I="0"+I)),"down"===_.direction&&(n>t||_.minus)||"up"===_.direction&&(t>n||_.minus)?(R=e.replace(v,i).replace(f,T).replace(g,L),R=R.replace(j,O).replace(w,M).replace(D,P).replace(y,I)):(R=e.replace(h,"00"),_.hasCompleted=!0),b.html(R).trigger("change.jcdevt",[_]).trigger("countChange",[_]),_.hasCompleted&&(b.trigger("complete.jcdevt").trigger("countComplete"),o(_.timer)),b.data("jcdData",_),void 0):!1},O={init:function(t){var a,o,d=e.extend({},n,t)
return this.each(function(){var n,i=e(this),r={}
if(i.data("jcdData")&&(i.countdown("changeSettings",t,!0),d=i.data("jcdData")),null===d.date)return e.error("No Date passed to jCountdown. date option is required."),!0
if(o=new Date(d.date),""+o=="Invalid Date"&&e.error("Invalid Date passed to jCountdown: "+d.date),o=null,d.onChange&&i.on("change.jcdevt",d.onChange),d.onComplete&&i.on("complete.jcdevt",d.onComplete),d.onPause&&i.on("pause.jcdevt",d.onPause),d.onResume&&i.on("resume.jcdevt",d.onResume),r=e.extend({},d),r.originalHTML=i.html(),r.dateObj=new Date(d.date),r.hasCompleted=!1,r.timer=0,r.yearsLeft=r.monthsLeft=r.weeksLeft=r.daysLeft=r.hrsLeft=r.minsLeft=r.secLeft=0,r.difference=null,null!==d.servertime){var s
a=new Date,s=e.isFunction(r.servertime)?r.servertime():r.servertime,r.difference=a.getTime()-s,s=null}n=e.proxy(L,i),r.timer=setInterval(n,r.updateTime),i.data("jcdData",r),n()})},changeSettings:function(t,n){return this.each(function(){var a,d,i=e(this),r=e.proxy(L,i)
return i.data("jcdData")?(a=e.extend({},i.data("jcdData"),t),t.hasOwnProperty("date")&&(d=new Date(t.date),""+d=="Invalid Date"&&e.error("Invalid Date passed to jCountdown: "+t.date)),a.hasCompleted=!1,a.dateObj=new Date(t.date),o(a.timer),i.off(".jcdevt").data("jcdData",a),n||(a.onChange&&i.on("change.jcdevt",a.onChange),a.onComplete&&i.on("complete.jcdevt",a.onComplete),a.onPause&&i.on("pause.jcdevt",a.onPause),a.onResume&&i.on("resume.jcdevt",a.onResume),a.timer=setInterval(r,a.updateTime),i.data("jcdData",a),r()),a=null,void 0):!0})},resume:function(){return this.each(function(){var t=e(this),n=t.data("jcdData"),a=e.proxy(L,t)
if(!n)return!0
if(t.data("jcdData",n).trigger("resume.jcdevt",[n]).trigger("countResume",[n]),!n.hasCompleted){if(n.timer=setInterval(a,n.updateTime),n.stopwatch&&"up"===n.direction){var o=C(t).getTime()-n.pausedAt.getTime(),d=new Date
d.setTime(n.dateObj.getTime()+o),n.dateObj=d}a()}})},pause:function(){return this.each(function(){var t=e(this),n=t.data("jcdData")
return n?(n.stopwatch&&(n.pausedAt=C(t)),o(n.timer),t.data("jcdData",n).trigger("pause.jcdevt",[n]).trigger("countPause",[n]),void 0):!0})},complete:function(){return this.each(function(){var t=e(this),n=t.data("jcdData")
return n?(o(n.timer),n.hasCompleted=!0,t.data("jcdData",n).trigger("complete.jcdevt").trigger("countComplete",[n]).off(".jcdevt"),void 0):!0})},destroy:function(){return this.each(function(){var t=e(this),n=t.data("jcdData")
return n?(o(n.timer),void t.off(".jcdevt").removeData("jcdData").html(n.originalHTML)):!0})},getSettings:function(t){var n=e(this),a=n.data("jcdData")
return t&&a?a.hasOwnProperty(t)?a[t]:void 0:a}}
return O[t]?O[t].apply(this,a.call(arguments,1)):"object"!=typeof t&&t?void e.error("Method "+t+" does not exist in the jCountdown Plugin"):O.init.apply(this,arguments)}}(jQuery)
